# Generated by Django 2.1.1 on 2018-09-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('designation', models.CharField(max_length=1024)),
                ('points', models.IntegerField()),
                ('price', models.FloatField()),
                ('province', models.CharField(max_length=1024)),
                ('region_1', models.CharField(max_length=1024)),
                ('region_2', models.CharField(max_length=1024)),
                ('taster_name', models.CharField(max_length=1024)),
                ('taster_twitter_handle', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('variety', models.CharField(max_length=1024)),
                ('winery', models.CharField(max_length=1024)),
            ],
        ),
    ]
