version: '3'

services: 
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    container_name: 'kickstarter_web'
    build: ./web
    env_file: .env
    volumes:
      - ./web/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /src/entrypoint.sh

volumes: 
  postgres_data: